# Generated by Django 4.2 on 2025-06-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_subjects_to_jsonfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="fen",
            field=models.CharField(
                default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKbnr w KQkq - 0 1",
                max_length=100,
            ),
        ),
    ]
