# Generated by Django 4.2 on 2025-06-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_game_fen"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="ai_difficulty",
            field=models.CharField(
                blank=True,
                choices=[("easy", "Easy"), ("normal", "Normal")],
                default="easy",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="is_vs_ai",
            field=models.BooleanField(default=False),
        ),
    ]
