# Generated by Django 4.2 on 2025-06-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_move_player"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="fen",
            field=models.CharField(
                default="rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
                max_length=100,
            ),
        ),
    ]
