# Generated by Django 4.2 on 2025-06-26 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_game_fen"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="avg_elo",
            field=models.IntegerField(
                default=1200,
                help_text="Average Elo of players for whom this quiz is intended",
            ),
        ),
        migrations.CreateModel(
            name="GameAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall", models.JSONField(blank=True, default=dict)),
                ("per_move", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "game",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="core.game",
                    ),
                ),
            ],
        ),
    ]
