# Generated by Django 4.2 on 2025-06-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_quizquestion_avg_elo_gameanalysis"),
    ]

    operations = [
        migrations.AddField(
            model_name="move",
            name="quiz_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
