# Generated by Django 4.2 on 2025-06-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_move_quiz_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="analysis_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Analysis"),
                    ("in_progress", "Analysis In Progress"),
                    ("completed", "Analysis Completed"),
                    ("failed", "Analysis Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
