# Generated by Django 4.2 on 2025-07-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_game_analysis_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="move",
            name="fen_before",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
